# Generated by Django 3.2.9 on 2021-11-29 08:08

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LegacySite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sensitive_data', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
            ],
        ),
    ]
